name: 'codetypo validator'
author: 'KhulnaSoft DevOps'
description: 'Shows codetypo errors as annotation (with file and code line) in GitHub Actions'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'search'
  color: 'green'
